[project]
name = "sqlitewrap"
version = "1.0.0"
description = "sqlitewrap: A simple Python wrapper for SQLite with built-in user authentication and database management."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
